<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">
    <link rel="stylesheet" href="res/css/main.css">
    <link rel="icon" href="favicon.ico" type="image/x-icon">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
          <ul class="nav navbar-nav">
            <div class="navbar-header">
              <a class="navbar-brand" href="index.php">
                <img alt="Brand" src="res/images/logo.png">
              </a>
           </div>
            <li><a href="index.php">Home</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="addItem#/addg">Video Games</a></li>
                <li><a href="#/consoles">Consoles</a></li>
                <li><a href="#/acc">Accessories</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/test/about">About</a></li>
            <li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{name}} <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Cart</a></li>
                <li><a href="#">Checkout</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Logout</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Change settings</a></li>
              </ul>
            </li>
          </ul>
      </div>
    </nav>
    <div class="container">
      {% block content %}
          {% block info %}{% endblock %}
      {% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/angular-route/angular-route.js"></script>
    <script src="res/js/main.js"></script>
    <script src="res/js/app.js"></script>
  </body>
</html>
